// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBuYs2RMh2SsaUI8Cq61h3qffMhzKKaM',
    appId: '1:575651805733:android:cfcdafc742475fef315dcc',
    messagingSenderId: '575651805733',
    projectId: 'dolapyonetim-43466',
    databaseURL: 'https://dolapyonetim-43466-default-rtdb.firebaseio.com',
    storageBucket: 'dolapyonetim-43466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVH_EyDsFdw9i9tjMdClJ7zJfus4PqdaI',
    appId: '1:575651805733:ios:266ca79db7c9dd30315dcc',
    messagingSenderId: '575651805733',
    projectId: 'dolapyonetim-43466',
    databaseURL: 'https://dolapyonetim-43466-default-rtdb.firebaseio.com',
    storageBucket: 'dolapyonetim-43466.appspot.com',
    iosClientId: '575651805733-v9em1r173s33uo33sli4a4pc0edqln2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dolapyonetim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4bxeP0UV5WD4b2oGQsNwbTZnQiRexnHE',
    appId: '1:575651805733:web:1df5ae375c244e2f315dcc',
    messagingSenderId: '575651805733',
    projectId: 'dolapyonetim-43466',
    authDomain: 'dolapyonetim-43466.firebaseapp.com',
    databaseURL: 'https://dolapyonetim-43466-default-rtdb.firebaseio.com',
    storageBucket: 'dolapyonetim-43466.appspot.com',
    measurementId: 'G-5PT9CD8CGH',
  );
}
